const replacements = [
  [/Por Que Ahora/g, "Por Qué Ahora"],
  [/Que es IA y que no es/g, "Qué es IA y qué no es"],
  [/Lo que si es/g, "Lo que sí es"],
  [/Proxima clase/g, "Próxima clase"],
  [/Pregunta guia/g, "Pregunta guía"],
  [/Lectura rapida/g, "Lectura rápida"],
  [/Diagnostico/g, "Diagnóstico"],
  [/Como se ve/g, "Cómo se ve"],
  [/Como usar/g, "Cómo usar"],
  [/Como interpretar/g, "Cómo interpretar"],
  [/Como leer/g, "Cómo leer"],
  [/Como cambia/g, "Cómo cambia"],
  [/Como sube/g, "Cómo sube"],
  [/Como priorizar/g, "Cómo priorizar"],
  [/Como mostrar/g, "Cómo mostrar"],
  [/Como corregir/g, "Cómo corregir"],
  [/Como detectar/g, "Cómo detectar"],
  [/Como va a medirla/g, "Cómo va a medirla"],
  [/Que decision mejora\?/g, "Qué decisión mejora?"],
  [/Que datos ya existen\?/g, "Qué datos ya existen?"],
  [/Que salida se espera\?/g, "Qué salida se espera?"],
  [/Que mirar primero/g, "Qué mirar primero"],
  [/Que parte si, que parte no/g, "Qué parte sí, qué parte no"],
  [/Que senal cambia que decision/g, "Qué señal cambia qué decisión"],
  [/Que tarea/g, "Qué tarea"],
  [/Que proceso/g, "Qué proceso"],
  [/Que fuentes/g, "Qué fuentes"],
  [/Que se puede hacer/g, "Qué se puede hacer"],
  [/Que tipo de/g, "Qué tipo de"],
  [/Que dimension/g, "Qué dimensión"],
  [/Que tramo/g, "Qué tramo"],
  [/Que accion cambia\?/g, "Qué acción cambia?"],
  [/Quien va a usarla\?/g, "Quién va a usarla?"],
  [/Por donde entrar primero/g, "Por dónde entrar primero"],
  [/por que ese antes que otro\?/g, "por qué ese antes que otro?"],
  [/cual seria/g, "cuál sería"],
  [/cual sirve/g, "cuál sirve"],
  [/Direccion/g, "Dirección"],
  [/direccion/g, "dirección"],
  [/Decision/g, "Decisión"],
  [/decision/g, "decisión"],
  [/Analisis/g, "Análisis"],
  [/analisis/g, "análisis"],
  [/Prediccion/g, "Predicción"],
  [/prediccion/g, "predicción"],
  [/Automatizacion/g, "Automatización"],
  [/automatizacion/g, "automatización"],
  [/Clasificacion/g, "Clasificación"],
  [/clasificacion/g, "clasificación"],
  [/Visualizacion/g, "Visualización"],
  [/visualizacion/g, "visualización"],
  [/Recoleccion/g, "Recolección"],
  [/recoleccion/g, "recolección"],
  [/Introduccion/g, "Introducción"],
  [/introduccion/g, "introducción"],
  [/Fidelizacion/g, "Fidelización"],
  [/fidelizacion/g, "fidelización"],
  [/Personalizacion/g, "Personalización"],
  [/personalizacion/g, "personalización"],
  [/Optimizacion/g, "Optimización"],
  [/optimizacion/g, "optimización"],
  [/Informacion/g, "Información"],
  [/informacion/g, "información"],
  [/Operacion/g, "Operación"],
  [/operacion/g, "operación"],
  [/Atencion/g, "Atención"],
  [/atencion/g, "atención"],
  [/Retencion/g, "Retención"],
  [/retencion/g, "retención"],
  [/Propension/g, "Propensión"],
  [/propension/g, "propensión"],
  [/Adopcion/g, "Adopción"],
  [/adopcion/g, "adopción"],
  [/Inversion/g, "Inversión"],
  [/inversion/g, "inversión"],
  [/Expansion/g, "Expansión"],
  [/expansion/g, "expansión"],
  [/Intervencion/g, "Intervención"],
  [/intervencion/g, "intervención"],
  [/Validacion/g, "Validación"],
  [/validacion/g, "validación"],
  [/Aprobacion/g, "Aprobación"],
  [/aprobacion/g, "aprobación"],
  [/Excepcion/g, "Excepción"],
  [/excepcion/g, "excepción"],
  [/Dimension/g, "Dimensión"],
  [/dimension/g, "dimensión"],
  [/Diseno/g, "Diseño"],
  [/diseno/g, "diseño"],
  [/Duracion/g, "Duración"],
  [/duracion/g, "duración"],
  [/Etica/g, "Ética"],
  [/etica/g, "ética"],
  [/Sesion/g, "Sesión"],
  [/sesion/g, "sesión"],
  [/Conversacion/g, "Conversación"],
  [/conversacion/g, "conversación"],
  [/Discusion/g, "Discusión"],
  [/discusion/g, "discusión"],
  [/Combinacion/g, "Combinación"],
  [/combinacion/g, "combinación"],
  [/Demografia/g, "Demografía"],
  [/demografia/g, "demografía"],
  [/Ambiguedad/g, "Ambigüedad"],
  [/ambiguedad/g, "ambigüedad"],
  [/Historico/g, "Histórico"],
  [/historico/g, "histórico"],
  [/Hipotesis/g, "Hipótesis"],
  [/hipotesis/g, "hipótesis"],
  [/Intuicion/g, "Intuición"],
  [/intuicion/g, "intuición"],
  [/Logica/g, "Lógica"],
  [/logica/g, "lógica"],
  [/Friccion/g, "Fricción"],
  [/friccion/g, "fricción"],
  [/Senales/g, "Señales"],
  [/senales/g, "señales"],
  [/Senal/g, "Señal"],
  [/senal/g, "señal"],
  [/Solucion/g, "Solución"],
  [/solucion/g, "solución"],
  [/Tecnologica/g, "Tecnológica"],
  [/tecnologica/g, "tecnológica"],
  [/Tecnologicos/g, "Tecnológicos"],
  [/tecnologicos/g, "tecnológicos"],
  [/Tecnicos/g, "Técnicos"],
  [/tecnicos/g, "técnicos"],
  [/Teoria/g, "Teoría"],
  [/teoria/g, "teoría"],
  [/Mecanica/g, "Mecánica"],
  [/mecanica/g, "mecánica"],
  [/Practica/g, "Práctica"],
  [/practica/g, "práctica"],
  [/Practico/g, "Práctico"],
  [/practico/g, "práctico"],
  [/Practicas/g, "Prácticas"],
  [/practicas/g, "prácticas"],
  [/Practicos/g, "Prácticos"],
  [/practicos/g, "prácticos"],
  [/Estrategica/g, "Estratégica"],
  [/estrategica/g, "estratégica"],
  [/Estrategicas/g, "Estratégicas"],
  [/estrategicas/g, "estratégicas"],
  [/Rapida/g, "Rápida"],
  [/rapida/g, "rápida"],
  [/Rapido/g, "Rápido"],
  [/rapido/g, "rápido"],
  [/Minimos/g, "Mínimos"],
  [/minimos/g, "mínimos"],
  [/Minimas/g, "Mínimas"],
  [/minimas/g, "mínimas"],
  [/Minima/g, "Mínima"],
  [/minima/g, "mínima"],
  [/Economias/g, "Economías"],
  [/economias/g, "economías"],
  [/Paises/g, "Países"],
  [/paises/g, "países"],
  [/Area/g, "Área"],
  [/area/g, "área"],
  [/Areas/g, "Áreas"],
  [/areas/g, "áreas"],
  [/Analitica/g, "Analítica"],
  [/analitica/g, "analítica"],
  [/Grafica/g, "Gráfica"],
  [/grafica/g, "gráfica"],
  [/Miercoles/g, "Miércoles"],
  [/miercoles/g, "miércoles"],
  [/Lideres/g, "Líderes"],
  [/lideres/g, "líderes"],
  [/Utiles/g, "Útiles"],
  [/utiles/g, "útiles"],
  [/Util/g, "Útil"],
  [/util/g, "útil"],
  [/Mas/g, "Más"],
  [/mas/g, "más"],
  [/Dano/g, "Daño"],
  [/dano/g, "daño"],
  [/Vacias/g, "Vacías"],
  [/vacias/g, "vacías"],
  [/Todavia/g, "Todavía"],
  [/todavia/g, "todavía"],
  [/Aun/g, "Aún"],
  [/aun/g, "aún"],
  [/Habra/g, "Habrá"],
  [/habra/g, "habrá"],
  [/Avanzara/g, "Avanzará"],
  [/avanzara/g, "avanzará"],
  [/Estudiara/g, "Estudiará"],
  [/estudiara/g, "estudiará"],
  [/Deberia/g, "Debería"],
  [/deberia/g, "debería"],
  [/Podria/g, "Podría"],
  [/podria/g, "podría"],
  [/Estaria/g, "Estaría"],
  [/estaria/g, "estaría"],
  [/Seria/g, "Sería"],
  [/seria/g, "sería"],
  [/Estetico/g, "Estético"],
  [/estetico/g, "estético"],
  [/unica/g, "única"],
  [/Unica/g, "Única"],
  [/Unico/g, "Único"],
  [/unico/g, "único"],
  [/Maximo/g, "Máximo"],
  [/maximo/g, "máximo"],
  [/Minimo/g, "Mínimo"],
  [/minimo/g, "mínimo"],
  [/Basica/g, "Básica"],
  [/basica/g, "básica"],
  [/Basico/g, "Básico"],
  [/basico/g, "básico"],
  [/Critica/g, "Crítica"],
  [/critica/g, "crítica"],
  [/Critico/g, "Crítico"],
  [/critico/g, "crítico"],
  [/Tecnico/g, "Técnico"],
  [/tecnico/g, "técnico"],
  [/Tecnica/g, "Técnica"],
  [/tecnica/g, "técnica"],
  [/Semantica/g, "Semántica"],
  [/semantica/g, "semántica"],
  [/Semantico/g, "Semántico"],
  [/semantico/g, "semántico"],
  [/Economico/g, "Económico"],
  [/economico/g, "económico"],
  [/Economica/g, "Económica"],
  [/economica/g, "económica"],
  [/Exposicion/g, "Exposición"],
  [/exposicion/g, "exposición"],
  [/Deteccion/g, "Detección"],
  [/deteccion/g, "detección"],
  [/Explicacion/g, "Explicación"],
  [/explicacion/g, "explicación"],
  [/Seleccion/g, "Selección"],
  [/seleccion/g, "selección"],
  [/Priorizacion/g, "Priorización"],
  [/priorizacion/g, "priorización"],
  [/Activacion/g, "Activación"],
  [/activacion/g, "activación"],
  [/Resolucion/g, "Resolución"],
  [/resolucion/g, "resolución"],
  [/Revision/g, "Revisión"],
  [/revision/g, "revisión"],
  [/Telefonia/g, "Telefonía"],
  [/telefonia/g, "telefonía"],
  [/Ubicacion/g, "Ubicación"],
  [/ubicacion/g, "ubicación"],
  [/Integracion/g, "Integración"],
  [/integracion/g, "integración"],
  [/Reputacion/g, "Reputación"],
  [/reputacion/g, "reputación"],
  [/Conversion/g, "Conversión"],
  [/conversion/g, "conversión"],
  [/Campanas/g, "Campañas"],
  [/campanas/g, "campañas"],
  [/Segmentacion/g, "Segmentación"],
  [/segmentacion/g, "segmentación"],
  [/Variacion/g, "Variación"],
  [/variacion/g, "variación"],
  [/Version/g, "Versión"],
  [/version/g, "versión"],
  [/Precision/g, "Precisión"],
  [/precision/g, "precisión"],
  [/Vision/g, "Visión"],
  [/vision/g, "visión"],
  [/Publico/g, "Público"],
  [/publico/g, "público"],
  [/Publica/g, "Pública"],
  [/publica/g, "pública"],
  [/Tipico/g, "Típico"],
  [/tipico/g, "típico"],
  [/Tipicos/g, "Típicos"],
  [/tipicos/g, "típicos"],
  [/Dificil/g, "Difícil"],
  [/dificil/g, "difícil"],
  [/Despues/g, "Después"],
  [/despues/g, "después"],
  [/Tambien/g, "También"],
  [/tambien/g, "también"],
  [/Proxima/g, "Próxima"],
  [/proxima/g, "próxima"],
  [/\bAsi\b/g, "Así"],
  [/\basi\b/g, "así"],
  [/\bAqui\b/g, "Aquí"],
  [/\baqui\b/g, "aquí"],
  [/\bAhi\b/g, "Ahí"],
  [/\bahi\b/g, "ahí"],
  [/a si /g, "así "],
];

export function accentText(value) {
  if (typeof value !== "string") {
    return value;
  }

  return replacements.reduce((result, [pattern, replacement]) => result.replace(pattern, replacement), value);
}

export function accentizeDeep(value) {
  if (typeof value === "string") {
    return accentText(value);
  }

  if (Array.isArray(value)) {
    return value.map((item) => accentizeDeep(item));
  }

  if (value && typeof value === "object") {
    return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, accentizeDeep(item)]));
  }

  return value;
}